# This is a basic workflow to help you get started with Actions

name: Release

on:  
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'
        required: true
        default: '1.0.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create GH release
      id: create_release
      uses: release-drafter/release-drafter@v5      
      with:
        name: v${{ github.event.inputs.tag }}
        tag: ${{ github.event.inputs.tag }}
        version: ${{ github.event.inputs.tag }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
